version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/python_project/api_cicd

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
